#! /bin/sh

web-ssh-241       /utage/git-log-stat /etc
web-ssh-251       /utage/git-log-stat /etc
web-ssh-254       /utage/git-log-stat /etc

web-ssh-251       /utage/git-log-stat /www
web-ssh-readynas  /utage/git-log-stat /c/media/Album
