#! /bin/sh

STYLE="m4v"
AUDIO="-N jpn -E faac  -6 dpl2 -R Auto -B 160 -D 2.0"
GRAPH="-l 1600 --crop 160:160:0:0 -e x264 -q 25 -r 29.97 --pfr --detelecine --decomb --encopts ref=6:weightp=1:subq=2:rc-lookahead=10:trellis=2:8x8dct=0:bframes=5:b-adapt=2"
HANDBRAKE="/usr/bin/HandBrakeCLI  -f mp4 -4  -O --verbose=1 "
OUT="/c/media/Album/Videos/MBP"
EXT="$*"

export STYLE
export AUDIO
export GRAPH
export HANDBRAKE
export OUT
export EXT
/utage/handbrake-worker

