#! /bin/sh

STYLE="m4v"
AUDIO="-N jpn -E faac  -6 dpl2 -R Auto -B 160 -D 2.0"
GRAPH="-e x264 -q 25 -r 29.97"
HANDBRAKE="/usr/bin/HandBrakeCLI -f mp4 -4  --verbose=1 --pfr --detelecine --decomb --encopts level=4.0:ref=6:weightp=1:subq=2:rc-lookahead=10:trellis=2:8x8dct=0:bframes=5:b-adapt=2"
OUT="/c/media/iPad/Videos"
EXT="$*"

export STYLE
export AUDIO
export GRAPH
export HANDBRAKE
export OUT
export EXT
/utage/handbrake-worker

