#! /bin/sh

echo enter title:
read title
test '' = "$title" && exit
find . -type f | grep "$title" | sort -r > /tmp/handbrake-src.txt
cat /tmp/handbrake-src.txt

echo enter grep:
read grep
cat /tmp/handbrake-src.txt | grep "$grep" > /tmp/handbrake.txt
cat /tmp/handbrake.txt

echo enter author:
read author
test '' = "$author" && exit
target="[$author] $title"

echo $target
mkdir -p "$OUT/$target"
ls       "$OUT/$target" || exit

cat /tmp/handbrake.txt | while read SRC
do
  postfix=` echo "$SRC" | sed -e "s/$author//g" | sed -e "s/$title//g" | sed -f /c/media/flatten-make.sed`
  DST="$target/$title-$postfix"
  echo "$DST"

  test -f "$OUT/$DST.$STYLE" || echo $HANDBRAKE $GRAPH $EXT $AUDIO -i \""$SRC"\" -o \""$OUT/$DST.$STYLE"\" >> ./handbrake.sh
done
