#! /bin/sh

for TO in $*
do
  for DIR in etc var home
  do
    rsync -r -e "ssh -p ${TO}0" /c/backup/$DIR/$TO/.git/ root@192.168.0.$TO:/$DIR/.git/
    ssh -p ${TO}0 root@192.168.0.$TO "cd /$DIR/  && git checkout ."
  done
done

