#! /bin/sh

for TO in $1
do
  mkdir -p etc/$TO/.git var/$TO/.git home/$TO/.git
  ssh -p ${TO}0 root@192.168.0.$TO  "
    cd /etc/   && git init && git add  /etc/fstab /etc/hosts /etc/ssh/sshd_config /etc/sysconfig/network-scripts/ifcfg-eth0 /etc/yum.repos.d
    cd /var/   && git init && git add  /var/spool/
    cd /home/  && git init
    yum update
  "

  if [ "241" = ${TO} ]
  then
    ssh -p ${TO}0 root@192.168.0.$TO  "
      cd /tmp/
      yum install lftp mongo-10gen python-devel
      wget http://downloads.sourceforge.net/project/librsync/librsync/0.9.7/librsync-0.9.7.tar.gz?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Flibrsync%2Ffiles%2Flibrsync%2F&ts=1336195911&use_mirror=jaist
      wget http://download.savannah.gnu.org/releases/rdiff-backup/rdiff-backup-1.3.3.tar.gz
      tar xvf librsync-0.9.7.tar.gz
      tar xvf rdiff-backup-1.3.3.tar.gz

      cd /tmp/librsync-0.9.7
      ./configure
      make AM_CFLAGS=-fPIC
      make install
      ldconfig

      cd /tmp/rdiff-backup-1.3.3
      python setup.py install
    "
  fi

  if ssh -p ${TO}0 root@192.168.0.$TO  "uname -m" | grep x86_64
  then
    ssh -p ${TO}0 root@192.168.0.$TO  "
      cd /tmp/
      wget http://pkgrepo.linuxtech.net/el6/release/x86_64/handbrake-cli-0.9.5-1.el6.x86_64.rpm
      wget http://rpms.famillecollet.com/enterprise/6/remi/x86_64/libdvdcss-1.2.12-1.el6.remi.x86_64.rpm
      rpm -i libdvdcss-1.2.12-1.el6.remi.x86_64.rpm
      rpm -i handbrake-cli-0.9.5-1.el6.x86_64.rpm
    "
  fi
done

