#!/bin/sh

nginx=/usr/local/nginx/sbin/nginx
conf=/utage/conf/nginx.conf
pid=/utage/pids/nginx.pid

case "$1" in
status)
  echo
  ps -A | grep $conf | grep master
  ls /utage/pids/*
  ;;
start)
  $nginx -c $conf
  ls -l $pid
  ;;
stop)
  cat $pid | xargs  kill -QUIT
  ;;
restart|reload)
  cat $pid | xargs  kill -HUP
  ;;
configtest)
  sudo $nginx -t -c $conf
  ;;
*)
  echo $"Usage: $0 {start|stop|restart|reload|configtest}"
esac

