#!/bin/sh

APP=/www/giji_rails
TARGET=253

/utage/ssh-$TARGET mkdir -p $APP/public
/utage/web-push-$TARGET $APP/public  --delete 1> /dev/null 2> /dev/null &

/utage/web-cleanup
/utage/web-release-to $TARGET 1> /dev/null 2> /dev/null &

