#!/bin/sh

. /utage/web-env

APP=giji_rails
PID=$APP.unicorn

cd /www/$APP

case "$1" in
status)
  echo
  ps -ef | grep $PID | grep master
  ls /utage/pids/*
  ;;
start)
  ~/.rbenv/bin/rbenv exec unicorn_rails -c /utage/conf/$PID.rb -E production -D
  ;;
stop)
  killall unicorn_rails
  ;;
restart)
  touch /www/$APP/tmp/restart.txt
  ;;
reload)
  $0 stop
  touch /www/$APP/tmp/restart.txt
  $0 start
  ;;
*)
  echo
  echo $"Usage: $0 command"
  echo
  echo  "  command : status start stop restart reload "
  echo  "  product : $APP"
esac
