#!/bin/sh

APP=/www/giji_rails
cd $APP

bundle update | grep -v Using
/utage/web-release-to 241 &
/utage/web-release-front &
/utage/web-release-worker &
/utage/ssh-254 /utage/web-app bundle-update | grep -v Using &
/utage/ssh-251 /utage/web-app bundle-update | grep -v Using &

