#!/bin/sh

redis_bin=/usr/local/bin/redis-server
mongod=/etc/init.d/mongod
redis=/etc/init.d/mongod

case "$1" in
status)
  echo
  ls /var/run/redis.pid && echo "redis (pid "`cat $pid`") を実行中..."
  $mongod status
  ps -A | grep $conf
  ;;
start-redis)
  $redis start
  ;;
start-mongo)
  $mongod start
  ;;
start)
  $redis start
  $mongod start
  ;;
stop)
  $redis stop
  $mongod stop
  ;;
restart|reload)
  $redis reload
  $mongod reload
  ;;
*)
  echo $"Usage: $0 {start|start-redis|start-mongo|stop|restart|reload}"
esac

