#!/bin/sh

echo "no: CookingDJ  to: $1  option: $2 $3 $4 $5"

TO=$1

rsync -e "ssh -p 3843" -r ${TO}/ 7korobi@183.181.54.214:${TO}/ --exclude='*.svn-base' --exclude='*.svn' --exclude='*.bak' $2 $3 $4 $5

