#!/bin/sh

RUBY=1.9.3-p194

test -d ruby-build || git clone git://github.com/sstephenson/ruby-build.git
cd ruby-build
git pull
./install.sh

rbenv install $RUBY
rbenv global  $RUBY
rbenv local   $RUBY
rbenv shell   $RUBY
rbenv rehash

cd /www/giji_rails
gem install bundler
rbenv exec bundle update

