#!/bin/sh

APP=/www/giji_rails
cd $APP

bundle update | grep -v Using
/utage/web-staging &
/utage/web-release
/utage/web-ssh-254 /utage/web-app bundle-update | grep -v Using &
/utage/web-ssh-253 /utage/web-app bundle-update | grep -v Using &
/utage/web-ssh-251 /utage/web-app bundle-update | grep -v Using &

