#!/bin/sh

nginx=/usr/local/bin/nginx
conf=/utage/conf/nginx.conf
pid=/utage/pids/nginx.pid

case "$1" in
start)
  sudo $nginx -c $conf
  ls -l $pid
  ;;
stop)
  cat $pid | xargs sudo kill -QUIT
  ;;
restart|reload)
  cat $pid | xargs sudo kill -HUP
  ;;
configtest)
  sudo $nginx -t -c $conf
  ;;
*)
  echo $"Usage: $0 {start|stop|restart|reload|configtest}"
esac

