DEFAULT_SSH: &DEFAULT_SSH_OPTIONS
  keys:
    - /home/7korobi/.ssh/id_rsa


PERJURY:
  ssh:
    open: vage.sakura.ne.jp
    user: vage
    options:
      <<: *DEFAULT_SSH_OPTIONS
    files:
      lsow:   /www/giji_log/sow
      lapp:   /www/sow-giji/cabala
      ldata:  /www/giji_log/vage
      lasset: /www
      data:   data/vil
      app:    /home/vage/www/perjury
      config: /home/vage/www/perjury
      asset:  /home/vage/www/perjury

XEBEC: 
  ssh:
    open: apollo.sakura.ne.jp
    user: apollo
    pass: coolteam
    options:
      <<: *DEFAULT_SSH_OPTIONS
    files:
      lsow:   /www/giji_log/sow
      lapp:   /www/sow-giji/cabala
      ldata:  /www/giji_log/xebec
      lasset: /www
      data:   data/vil
      app:    /home/apollo/www/sow/xebec
      config: /home/apollo/www/sow/xebec
      asset:  /home/apollo/www/sow

CABALA: 
  ssh:
    open: aocafe.sakura.ne.jp
    user: aocafe
    pass: minato
    options:
      <<: *DEFAULT_SSH_OPTIONS
    files:
      lsow:   /www/giji_log/sow
      lapp:   /www/sow-giji/cabala
      ldata:  /www/giji_log/cafe
      lasset: /www
      data:   data/vil
      app:    /home/aocafe/www/noir/cafe
      config: /home/aocafe/www/noir/cafe
      asset:  /home/aocafe/www/noir

ALLSTAR: 
  ssh:
    open: jinro.jksy.org
    user: nanakorobi
    pass: 7korobi
    options:
      <<: *DEFAULT_SSH_OPTIONS
      port: 20002
    files:
      lsow:   /www/giji_log/sow
      lapp:   /www/sow-giji/cabala
      ldata:  /www/giji_log/jksy
      lasset: /www
      data:   data/vil
      app:    /home/nanakorobi/public_html
      config: /home/nanakorobi/public_html
      asset:  /home/nanakorobi/public_html

CRAZY: 
  ftp:
    open: crazy-crazy.sakura.ne.jp
    user: crazy-crazy
    pass: yhvxa3vwh6
    files:
      ldata:  /www/giji_log/crazy
      data:   data/vil
      config: /home/crazy-crazy/www/crazy

LOBBY: 
  ftp:
    open: crazy-crazy.sakura.ne.jp
    user: crazy-crazy
    pass: yhvxa3vwh6
    files:
      lsow:   /www/giji_log/sow
      lapp:   /www/sow-giji/cabala
      ldata:  /www/giji_log/lobby
      lasset: /www
      data:   data/vil
      app:    /home/crazy-crazy/www/giji_lobby/lobby
      config: /home/crazy-crazy/www/giji_lobby/lobby
      asset:  /home/crazy-crazy/www

OFFPARTY: 
  ftp:
    open: party.ps.land.to
    user: party
    pass: TyaboFil20
    files:
      lapp:   /www/sow-giji/cabala
      ldata:  /www/giji_log/kitchen
      data:   data/vil
      app:    /public_html/lobby
      config: /public_html/kitchen

