:verbose: false
:pidfile: /www/giji-rails/pids/queue.pid
:logfile: /www/giji-rails/log/sidekiq.log
:concurrency: 1
:queues:
  - giji_rsyncs
  - giji_schedules
  - giji_vils
  - giji_freeze
  - giji_errors
